services: 
  backend_django:
    build:
      context: ./backend_django
    command: wait-for-it.sh database_mysql:3306 -t 0 -- docker-entrypoint.sh
    image: inntale_backend:1.0
    ports:
      - 8000:8000
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PSW=${MYSQL_PSW}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_HOST_PORT=${MYSQL_HOST_PORT}
    restart: on-failure
    depends_on:
      - database_mysql
    volumes:
      - ./backend_django:/app

  database_mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PSW}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PSW}
    volumes:
      - mysqldata:/var/lib/mysql
      - ./backend_django/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    restart: unless-stopped


volumes:
  mysqldata: