# Generated by Django 5.1.4 on 2024-12-15 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('season', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(unique=True)),
                ('is_edited', models.BooleanField()),
                ('youtube_link', models.TextField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='campaigns.manual')),
            ],
        ),
    ]
