# Generated by Django 5.1.4 on 2024-12-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='slug',
            field=models.SlugField(default='empty'),
        ),
    ]
