# Generated by Django 5.1.4 on 2024-12-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_manual_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
