# Generated by Django 5.1.4 on 2024-12-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_manual_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
