# Generated by Django 5.1.4 on 2024-12-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_player_alter_campaign_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
