# Generated by Django 5.1.4 on 2024-12-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_cast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manual',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='player',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
