# Generated by Django 5.1.4 on 2025-01-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_player_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='image',
            new_name='profile_pic',
        ),
    ]
