# Generated by Django 5.1.4 on 2025-01-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_rename_image_player_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='players/'),
        ),
    ]
