# Generated by Django 5.1.4 on 2025-01-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_alter_player_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/'),
        ),
    ]
