# Generated by Django 5.1.4 on 2025-06-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='character',
            field=models.CharField(max_length=255),
        ),
    ]
