# Generated by Django 5.1.4 on 2025-06-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_alter_cast_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='manual',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
