# Generated by Django 5.1.4 on 2025-06-10 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_setting_alter_manual_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='setting',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaigns', to='campaigns.setting'),
        ),
    ]
