# Generated by Django 5.1.4 on 2025-06-10 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0019_campaign_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaigns', to='campaigns.setting'),
        ),
    ]
