# Generated by Django 5.1.4 on 2025-06-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0020_alter_campaign_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='manuals'),
        ),
    ]
