# Generated by Django 5.1.4 on 2025-06-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0021_manual_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='settings'),
        ),
    ]
