# Generated by Django 5.1.4 on 2025-07-03 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0022_setting_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manual',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'ordering': ['name']},
        ),
    ]
